### ISSUE TITLE
Add black background option :)

### ISSUE THREAD

**Issue by ghost** [agruzdev/ShibaView#2]
I would like to ask the ShibaView developer to add the 100% black background option for viewing images in Windows 11 and if possible add a button at the top to close ShibaView with one click :) (a close button that only appears when swiping the cursor above it in the upper right part of the screen) would be very useful!!

**Comment by agruzdev** [comment]
Hello.
Thank you for the request, I think, I will add a settings window to setup things like these. 

As quick solution for background color you can use regedit and change this variable to #000000
HKEY_CURRENT_USER\Software\Alexey Gruzdev\ShibaView\canvas\background

![image](https://github.com/agruzdev/ShibaView/assets/5796881/3931996b-519e-48d1-9bed-8dd5c48c11a6)

Sorry for slow replies during NY holidays

**Comment by agruzdev** [comment]
Done in Release v1.12
https://github.com/agruzdev/ShibaView/releases/tag/v1.12

**Comment by agruzdev** [comment]
Use F9 to open the Settings menu

**Comment by ghost** [comment]
infelizmente as modificações não se mantem depois de fechar o shibaview.

**Comment by agruzdev** [comment]
> infelizmente as modificações não se mantem depois de fechar o shibaview.

All settings are stored in a local file named "Settings.ini". Please make sure that ShibaView.exe has permissions to write to own directory. 
Maybe you have put the ShibaView directory to the Program Files and Windows needs Administrative permissions to create new files there?
